### ISSUE TITLE
auto_now and auto_now_add are ignored

### ISSUE THREAD

**Issue by M1ha-Shvn** [M1ha-Shvn/django-pg-bulk-update#55]
[DateField](https://docs.djangoproject.com/en/3.0/ref/models/fields/#datefield) and [DateTimeField](https://docs.djangoproject.com/en/3.0/ref/models/fields/#datetimefield) in django can have `auto_now` and `auto_now_add` parameters, generating current date or datetime on save. But these are not implemented as defaults and `has_default` method returns `False` for fields with these attributes. As a result this library methods ignore it.

**Comment by M1hacka** [comment]
Fixed.

**Comment by M1ha-Shvn** [comment]
Fixed by https://github.com/M1ha-Shvn/django-pg-bulk-update/pull/62

**Comment by M1ha-Shvn** [comment]
Released [v3.4.0](https://github.com/M1ha-Shvn/django-pg-bulk-update/releases/tag/v3.4.0)
