### ISSUE TITLE
SQL generation fails when the model table name is already quoted

### ISSUE THREAD

**Issue by ryanhennig** [M1ha-Shvn/django-pg-bulk-update#63]
Error encountered: django.db.utils.ProgrammingError: zero-length delimited identifier at or near """"

This issue occurs when attempting to do a bulk_update_or_create with a model which already has double-quotes in the table name. This occurs if you define your model with a table_name which includes a double-quoted schema name prefix, like so:

class MyModel(models.Model):
    class Meta:
        db_table = '"schema"."mymodel"'

**Comment by M1ha-Shvn** [comment]
Thanks for report and PR. I'll watch review your [PR](https://github.com/M1ha-Shvn/django-pg-bulk-update/pull/64) as soon as possible

**Comment by M1ha-Shvn** [comment]
Released [v3.4.1](https://github.com/M1ha-Shvn/django-pg-bulk-update/releases/tag/v3.4.1)
