### ISSUE TITLE
It is not possible to explicitly set the value of `auto_now` or `auto_now_add` fields, even when passing a set function

### ISSUE THREAD

**Issue by dhendry** [M1ha-Shvn/django-pg-bulk-update#76]
I have a usecase where I want to explicitly set the value of an `auto_now_add` datetime field. Using this library, it does not look like this is possible, even if I pass an explicit set function.

I believe this may just be a small oversight in the implementation of `django_pg_bulk_update.query._validate_set_functions()` where it does not respect overrides due to the ordering.

![image](https://user-images.githubusercontent.com/2521996/136249038-938f2957-25f6-487d-81c4-729ed4e6579b.png)

Love this library by the way!

**Comment by M1ha-Shvn** [comment]
I've also added python 3.10 and postgres 13 testing to GitHub Actions.
Here is [the PR](https://github.com/M1ha-Shvn/django-pg-bulk-update/pull/78) which contains your changes + minor test and linter fixes. As soon as it passes all the tests, I'll make a release.
